name: vpn_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sizer: ^3.0.5
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3
  dio: ^5.8.0+1
  intl: ^0.20.2
  firebase_core: ^3.13.0
  firebase_analytics: ^11.4.5
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  path_provider: ^2.1.5
  fl_chart: ^0.70.2
  mockito: ^5.4.5

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
